services:
    admin.user:
        class: AdminBundle\Admin\UserAdmin
        arguments: [~, UserBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User, group: User}
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    admin.advert:
            class: AdminBundle\Admin\AdvertAdmin
            arguments: [~, AdvertBundle\Entity\Advert, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Advert, group: Advert }