<?php

namespace AdvertBundle\Repository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByMarque($marque)
    {
        return $this->createQueryBuilder("u")
            ->where("u.carModel LIKE :term")
            ->setParameter("term", "%".$marque."%")
            ->getQuery()->getArrayResult();
    }

}
